# DS-Containers/docker-compose.yml
version: '3.8'

services:
  # MLflow Tracking Server Service
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_tracking_server
    ports:
      - '5000:5000'
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_ARTIFACT_URI: ${MLFLOW_ARTIFACT_URI}
    volumes:
      - ./reports:/reports
      - ./app:/app
      - ./data:/data
    restart: always
    command: mlflow ui --host 0.0.0.0 --port 5000

  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: restaurant_streamlit_ui
    ports:
      - '8504:8501' # Streamlit UI port (Host:Container)
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000 # Streamlit connects to MLflow server
    volumes:
      - ./app:/app
      - ./data:/data
      - ./reports:/reports
    depends_on:
      - mlflow-server
    restart: always
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
# No named volumes needed as we are using bind mounts directly
# volumes:
#   mlflow_artifacts:
