# DS-Containers/Dockerfile.mlflow
FROM python:3.10-slim-buster

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY app/ .

EXPOSE 5000
# CMD is defined in docker-compose.yml